services:
  db:
    build: .
    # image: demo-postgres
    restart: always
    environment:
      DB_NAME: "test_app"
      DB_USER: "user"
      DB_PASS: "pass"
    ports:
      - "5432:5432"
    volumes:
      - postgres_demo:/var/lib/postgresql/data
volumes:
  postgres_demo: